//! Claude Code から呼び出される hook ラッパースクリプト
//! (`~/.ccc/bin/ccc-hook.sh`) の生成・配信。
//!
//! Claude Code の `settings.json` には ccc 再起動を跨いで変わらないパス
//! (= このラッパースクリプト) を登録しておき、ccc 起動ごとに最新の
//! `CCC_HOOK_ENDPOINT` / `CCC_SESSION_TOKEN` を埋め込んだ内容で
//! ファイルを atomic に書き換える。
//!
//! tmux session の env として焼き込まれてしまう「動的ポート + ランダム
//! トークン」を `settings.json` 経由のスクリプト書き換えに逃がすことで、
//! ccc 再起動 → port/token 変化 → 復元中インスタンスの hook が
//! 全部 401/接続拒否、という問題を回避する。
//!
//! ## 安全性
//!
//! - `endpoint` は `http://127.0.0.1:<u16>/hook` 形式に限定する想定
//! - `token` は `[A-Za-z0-9]` のみ。`rand::distributions::Alphanumeric` は
//!   ASCII 英数字のみを生成するので shell single-quote 内に直接埋め込んで安全
//! - 想定外の文字が混入した場合は `validate_token` / `validate_endpoint` が
//!   エラーを返し、書き出しを拒否する（権限昇格やコマンドインジェクションの
//!   保険）

use anyhow::{anyhow, Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

use super::hook_bin_dir;

/// settings.json から参照される wrapper script のファイル名。
pub const WRAPPER_SCRIPT_NAME: &str = "ccc-hook.sh";

/// hook receiver と疎通するための情報。
#[derive(Debug, Clone)]
pub struct HookCredentials<'a> {
    /// `http://127.0.0.1:<port>/hook` 形式の受信エンドポイント
    pub endpoint: &'a str,
    /// 認証 Bearer token（`[A-Za-z0-9]` のみを期待）
    pub token: &'a str,
}

/// ローカル `~/.ccc/bin/ccc-hook.sh` を最新の `creds` で atomic に書き換える。
/// 既存ファイルは tempfile + rename で差し替えるので、書き換え中の hook 起動も
/// 古い内容を最後まで読みきった上で exec できる。
pub fn write_local(creds: &HookCredentials<'_>) -> Result<PathBuf> {
    validate_endpoint(creds.endpoint)?;
    validate_token(creds.token)?;

    let dir = hook_bin_dir()?;
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("ディレクトリ作成失敗: {}", dir.display()))?;
    let target = dir.join(WRAPPER_SCRIPT_NAME);
    let tmp = dir.join(format!(".{WRAPPER_SCRIPT_NAME}.tmp"));

    let content = render_script(creds);
    std::fs::write(&tmp, content.as_bytes())
        .with_context(|| format!("一時ファイル書き出し失敗: {}", tmp.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&tmp)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&tmp, perms)?;
    }

    std::fs::rename(&tmp, &target).with_context(|| {
        format!(
            "atomic rename 失敗: {} → {}",
            tmp.display(),
            target.display()
        )
    })?;
    Ok(target)
}

/// リモートホストの `~/.ccc/bin/ccc-hook.sh` を scp で最新内容に上書きする。
///
/// 呼び出し前提:
/// - リモートに `~/.ccc/bin/` が既に存在する（`install_remote` で作成済み）
/// - hook バイナリ本体 `ccc-claude-code-hook` も同ディレクトリに配置済み
///
/// 動的ポートとトークンを埋め込むため、ccc を再起動するたびに（あるいは
/// 復元/再接続のたびに）呼び直す必要がある。
pub fn install_remote(host_alias: &str, creds: &HookCredentials<'_>) -> Result<()> {
    validate_endpoint(creds.endpoint)?;
    validate_token(creds.token)?;

    // 同じ内容のテンプを scp で送る。`scp -p` でモードも持ち上がるが、リモート側で
    // 後段の `chmod 755` を打って確実に実行可能にする。
    let content = render_script(creds);
    // セキュリティ: 同一プロセス内に他のユーザーがいないことを前提に temp_dir を使う。
    // pid 込みで一意化、書き出し後すぐ scp して削除する。
    let tmp =
        std::env::temp_dir().join(format!("ccc-hook-{}-{}.sh", std::process::id(), host_alias));
    std::fs::write(&tmp, content.as_bytes())
        .with_context(|| format!("一時ファイル書き出し失敗: {}", tmp.display()))?;

    let scp_target = format!("{host_alias}:.ccc/bin/{WRAPPER_SCRIPT_NAME}");
    let scp_status = Command::new("scp")
        .args(["-q", "-p"])
        .arg(&tmp)
        .arg(&scp_target)
        .status();
    let _ = std::fs::remove_file(&tmp);

    match scp_status {
        Ok(s) if s.success() => {}
        Ok(s) => return Err(anyhow!("scp が失敗: {s}")),
        Err(e) => return Err(anyhow!("scp 起動失敗: {e}")),
    }

    let chmod = Command::new("ssh")
        .args([
            host_alias,
            &format!("chmod 755 ~/.ccc/bin/{WRAPPER_SCRIPT_NAME}"),
        ])
        .status()
        .with_context(|| "ssh chmod 失敗".to_string())?;
    if !chmod.success() {
        return Err(anyhow!("リモート chmod が失敗: {chmod}"));
    }
    Ok(())
}

/// ラッパースクリプトの本文を返す。テスト容易性のために pure 関数にしてある。
///
/// validate_* を通過した `creds` を渡すこと（single-quote 内に安全に埋め込める前提）。
///
/// `--pane-died <exit_status> <instance_id>` モードは tmux の `pane-died` フック
/// （`pty_instance` が session 作成時に仕込む）から呼ばれ、PaneDied イベントを
/// hook バイナリの stdin 転送経路に流す。バイナリ自体は無変更で済む
/// （クロスコンパイル済みバイナリの再生成が不要）。
fn render_script(creds: &HookCredentials<'_>) -> String {
    format!(
        "#!/bin/sh\n\
         # Generated by ccc on each startup. Do not edit; changes will be lost.\n\
         if [ \"$1\" = \"--pane-died\" ]; then\n\
         \u{0020}\u{0020}[ -n \"$3\" ] || exit 0\n\
         \u{0020}\u{0020}printf '{{\"hook_event_name\":\"PaneDied\",\"exit_status\":\"%s\"}}' \"${{2:-unknown}}\" | \\\n\
         \u{0020}\u{0020}\u{0020}\u{0020}CCC_HOOK_ENDPOINT='{endpoint}' \\\n\
         \u{0020}\u{0020}\u{0020}\u{0020}CCC_SESSION_TOKEN='{token}' \\\n\
         \u{0020}\u{0020}\u{0020}\u{0020}CCC_INSTANCE_ID=\"$3\" \\\n\
         \u{0020}\u{0020}\u{0020}\u{0020}\"$HOME/.ccc/bin/ccc-claude-code-hook\"\n\
         \u{0020}\u{0020}exit 0\n\
         fi\n\
         exec env \\\n\
         \u{0020}\u{0020}CCC_HOOK_ENDPOINT='{endpoint}' \\\n\
         \u{0020}\u{0020}CCC_SESSION_TOKEN='{token}' \\\n\
         \u{0020}\u{0020}\"$HOME/.ccc/bin/ccc-claude-code-hook\" \"$@\"\n",
        endpoint = creds.endpoint,
        token = creds.token,
    )
}

/// endpoint は `http://127.0.0.1:<u16>/hook` 形式のみを許可する。
/// それ以外の文字（特に single-quote / `$` / backslash）が混入していたら
/// スクリプトに埋め込まずエラーで弾く。
fn validate_endpoint(endpoint: &str) -> Result<()> {
    let prefix = "http://127.0.0.1:";
    let suffix = "/hook";
    let rest = endpoint
        .strip_prefix(prefix)
        .and_then(|s| s.strip_suffix(suffix))
        .ok_or_else(|| anyhow!("hook endpoint 形式が不正: {endpoint:?}"))?;
    if rest.is_empty() || !rest.chars().all(|c| c.is_ascii_digit()) {
        return Err(anyhow!("hook endpoint のポート部が不正: {endpoint:?}"));
    }
    Ok(())
}

/// token は `[A-Za-z0-9]` のみを許可する。
/// `rand::distributions::Alphanumeric` の出力仕様と整合させる。
fn validate_token(token: &str) -> Result<()> {
    if token.is_empty() {
        return Err(anyhow!("hook token が空"));
    }
    if !token.chars().all(|c| c.is_ascii_alphanumeric()) {
        return Err(anyhow!(
            "hook token に英数字以外の文字が含まれています (実装上のバグ)"
        ));
    }
    Ok(())
}

/// 既知の hook 関連実行ファイルパス（ラッパー / バイナリ）の絶対パスから basename
/// を取り出し、ccc 由来か判定する用途で他モジュールから呼ばれる。
pub fn is_ccc_hook_filename(name: &str) -> bool {
    matches!(name, WRAPPER_SCRIPT_NAME_STR | LEGACY_BINARY_NAME)
}

const WRAPPER_SCRIPT_NAME_STR: &str = WRAPPER_SCRIPT_NAME;
const LEGACY_BINARY_NAME: &str = "ccc-claude-code-hook";

/// 補助: `Path` から basename を抽出して `is_ccc_hook_filename` に渡す。
pub fn path_is_ccc_hook(path: &str) -> bool {
    // settings.json の `command` は引数を含むことがあるため、先頭トークンの basename を見る。
    // `split_whitespace` は先頭の空白も無視するので明示の `trim` は不要。
    let first = path.split_whitespace().next().unwrap_or("");
    Path::new(first)
        .file_name()
        .and_then(|n| n.to_str())
        .map(is_ccc_hook_filename)
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_creds() -> HookCredentials<'static> {
        HookCredentials {
            endpoint: "http://127.0.0.1:54321/hook",
            token: "abcXYZ0123",
        }
    }

    #[test]
    fn render_contains_shebang_and_exec_env() {
        let s = render_script(&sample_creds());
        assert!(s.starts_with("#!/bin/sh\n"));
        assert!(s.contains("exec env"));
        assert!(s.contains("CCC_HOOK_ENDPOINT='http://127.0.0.1:54321/hook'"));
        assert!(s.contains("CCC_SESSION_TOKEN='abcXYZ0123'"));
        assert!(s.contains(r#""$HOME/.ccc/bin/ccc-claude-code-hook""#));
        assert!(s.contains(r#""$@""#));
    }

    #[test]
    fn validate_endpoint_accepts_loopback() {
        assert!(validate_endpoint("http://127.0.0.1:1/hook").is_ok());
        assert!(validate_endpoint("http://127.0.0.1:65535/hook").is_ok());
    }

    #[test]
    fn validate_endpoint_rejects_other_hosts() {
        assert!(validate_endpoint("http://localhost:54321/hook").is_err());
        assert!(validate_endpoint("http://example.com:54321/hook").is_err());
        assert!(validate_endpoint("http://127.0.0.1:54321/hook/extra").is_err());
        // single-quote 混入は loopback 形式に当てはまらない時点で reject
        assert!(validate_endpoint("http://127.0.0.1:54321'/hook").is_err());
    }

    #[test]
    fn validate_endpoint_rejects_non_numeric_port() {
        assert!(validate_endpoint("http://127.0.0.1:abc/hook").is_err());
        assert!(validate_endpoint("http://127.0.0.1:/hook").is_err());
    }

    #[test]
    fn validate_token_accepts_alnum() {
        assert!(validate_token("abcXYZ0123").is_ok());
        assert!(validate_token("A").is_ok());
    }

    #[test]
    fn validate_token_rejects_empty_or_special() {
        assert!(validate_token("").is_err());
        assert!(validate_token("abc'def").is_err());
        assert!(validate_token("abc def").is_err());
        assert!(validate_token("abc$def").is_err());
        assert!(validate_token("abc-def").is_err()); // ハイフンも禁止（Alphanumeric の仕様外）
    }

    #[test]
    fn is_ccc_hook_filename_matches_both_names() {
        assert!(is_ccc_hook_filename("ccc-hook.sh"));
        assert!(is_ccc_hook_filename("ccc-claude-code-hook"));
        assert!(!is_ccc_hook_filename("other-hook"));
        assert!(!is_ccc_hook_filename(""));
    }

    #[test]
    fn path_is_ccc_hook_recognizes_paths() {
        assert!(path_is_ccc_hook("/Users/me/.ccc/bin/ccc-hook.sh"));
        assert!(path_is_ccc_hook("~/.ccc/bin/ccc-hook.sh"));
        assert!(path_is_ccc_hook("~/.ccc/bin/ccc-claude-code-hook"));
        assert!(path_is_ccc_hook("ccc-hook.sh"));
        assert!(!path_is_ccc_hook("/usr/bin/other"));
        assert!(!path_is_ccc_hook(""));
    }
}
